name: Benchmark

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code ğŸ“‚
      uses: actions/checkout@v3

    - name: Set up Python ğŸ
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies ğŸ› ï¸
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ray dask[distributed]
        pip install memory-profiler matplotlib

    - name: Run benchmark and create plots ğŸ“ˆ
      run: |
        python benchmark.py

    - name: Upload plots ğŸ“¤
      uses: actions/upload-artifact@v3
      with:
        name: plots
        path: benchmark_results.png

  comment:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
    - name: Checkout code ğŸ“‚
      uses: actions/checkout@v3

    - name: Download plots ğŸ’¾
      uses: actions/download-artifact@v3
      with:
        name: plots

    - name: Comment on PR ğŸ’¬
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.number }} # 1
        body: |
          ### Benchmark Plots

          Previous Benchmark:
          ![Previous Benchmark](assets/benchmark_results.png)

          New Benchmark:
          ![New Benchmark](benchmark_results.png)
        reactions: 'eyes'
